# Autogenerated by devscripts/update-version.py

__version__ = '2023.03.19.183130'

RELEASE_GIT_HEAD = '3108de1abce560dc1b43c25d7a2e3e7fafd6d5e7'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'stable'
